= QueryDsl demo

== Intro

Sample project for QueryDsl testing.

The project contains all the setup needed for spring boot, querydsl-sql, test code generation and
thus makes it easier to start with querydsl using Spring.

Project uses:

* spring boot - https://projects.spring.io/spring-boot/
* liquibase - http://www.liquibase.org/
* postgres database - for main source code - https://www.postgresql.org/
* H2 - for tests

Project sets up logging to minimum, to see SQL's generated by querydsl.

== Postgres database

To quickly run postgres database execute run postgres container defined in docker-compose.yaml.

You need docker-compose - https://docs.docker.com/compose/gettingstarted/

 $ docker-compose up -d

=== Database updates

Liquibase is disabled by default in application.properties file.

 spring.liquibase.enabled=false

The database changes can be applied by executing from command line:

 $ ./gradlew update

=== QueryDsl model re-generation

jOOQ model is stored in _gensrc_ directory.

After change in database tables one have to re-generate jOOQ model.

To re-generate jOOQ model:

[source,bash]
----
$ mvn clean process-resources liquibase:update
$ rm -rf gensrc
$ mvn clean generate-sources -Pjooq-generate
----

Afterwards one have to manually add/remove jOOQ model files to git.

== Sample code

Sample code using jOOQ is placed in class pl.jdata.samples.jooqsample.JooqUsageSample
